host:
  ip: 0.0.0.0
  port: "8333"
logs:
  level: info
  path: ./logs/logrus.log

dir:
  root: "/home"
key: "123"
user:
  root:
    permission: "root"
    password: "root"
  default:
    permission: "default"
    password: "123456"
  anubis:
    permission: "root"
    password: "password"