dir:
    root: /home
    tmp: /tmp
host:
    ip: 0.0.0.0
    port: "9090"
logs:
    level: info
    path: ./logs/logrus.log
user:
    default:
        mod: default
        password: "123456"
    root:
        mod: root
        password: root
